# ruff: noqa: D415, INP001
"""initial

Revision ID: 5e8b5585c484
Revises:
Create Date: 2024-12-30 10:18:07.012384

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5e8b5585c484"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "creation_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("contents", sa.String(), nullable=False),
        sa.Column("category", sa.String(), server_default="", nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
