---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages:
  - commit
  - merge-commit

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        # Ruff finds pyproject.toml automatically, so there's no reason to pass it.
        args:
          - --select
          - I
          - --fix
      - id: ruff-format

  # Mypy needs to understand the imports, so it needs to be run from the Poetry venv,
  # and not an isolated one, which is the default with pre-commit.
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        # pre-commit will run from the repo root. We need to adjust for that.
        entry: poetry -C demo-projects/python-backend run mypy
        language: system
        types: [python]
