---
services:

  api:
    # This version of the command will reload the web app on file changes automatically.
    # There's `make run_reloading` for that purpose as well, but this is for developers who can't run `entr`.
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8080", "sample_backend.main:app", "--reload"]
    # Helps with development by mounting the code directly into the container.
    volumes:
      - ./sample_backend/:/app/sample_backend/
